<?php



namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionTableSeeder extends Seeder

{

    /**

     * Run the database seeds.

     */

    public function run(): void

    {

        $permission = [

            [
                'name' => 'sanctum.csrf-cookie',
                'action' => 'Laravel\Sanctum\Http\Controllers\CsrfCookieController@show',
                'route' => 'sanctum.csrf-cookie',
                'url' => 'sanctum/csrf-cookie',
                'method' => 'GET|HEAD',
                'prefix' => 'sanctum',
            ],
            [
                'name' => 'ignition.healthCheck',
                'action' => 'Spatie\LaravelIgnition\Http\Controllers\HealthCheckController',
                'route' => 'ignition.healthCheck',
                'url' => '_ignition/health-check',
                'method' => 'GET|HEAD',
                'prefix' => 'ignition',
            ],
            [
                'name' => 'ignition.executeSolution',
                'action' => 'Spatie\LaravelIgnition\Http\Controllers\ExecuteSolutionController',
                'route' => 'ignition.executeSolution',
                'url' => '_ignition/execute-solution',
                'method' => 'POST',
                'prefix' => 'ignition',
            ],
            [
                'name' => 'ignition.updateConfig',
                'action' => 'Spatie\LaravelIgnition\Http\Controllers\UpdateConfigController',
                'route' => 'ignition.updateConfig',
                'url' => '_ignition/update-config',
                'method' => 'POST',
                'prefix' => 'ignition',
            ],
            [
                'name' => '',
                'action' => 'Closure',
                'route' => '',
                'url' => 'api/user',
                'method' => 'GET|HEAD',
                'prefix' => '',
            ],
            [
                'name' => 'website',
                'action' => 'App\Http\Controllers\BasicController@website',
                'route' => 'website',
                'url' => '/',
                'method' => 'GET|HEAD',
                'prefix' => 'website',
            ],
            [
                'name' => 'client.registration',
                'action' => 'App\Http\Controllers\BasicController@clientRegistration',
                'route' => 'client.registration',
                'url' => 'client/registration',
                'method' => 'GET|HEAD',
                'prefix' => 'client',
            ],
            [
                'name' => 'tmp.client.store',
                'action' => 'App\Http\Controllers\BasicController@clientStore',
                'route' => 'tmp.client.store',
                'url' => 'tmp/client/store',
                'method' => 'POST',
                'prefix' => 'tmp',
            ],
            [
                'name' => 'dashboard',
                'action' => 'App\Http\Controllers\BasicController@dashboard',
                'route' => 'dashboard',
                'url' => 'dashboard',
                'method' => 'GET|HEAD',
                'prefix' => 'dashboard',
            ],
            [
                'name' => 'logs',
                'action' => 'App\Http\Controllers\BasicController@Logs',
                'route' => 'logs',
                'url' => 'logs',
                'method' => 'GET|HEAD',
                'prefix' => 'logs',
            ],
            [
                'name' => 'users.index',
                'action' => 'App\Http\Controllers\UserController@index',
                'route' => 'users.index',
                'url' => 'admin/users',
                'method' => 'GET|HEAD',
                'prefix' => 'users',
            ],
            [
                'name' => 'users.create',
                'action' => 'App\Http\Controllers\UserController@create',
                'route' => 'users.create',
                'url' => 'admin/users/create',
                'method' => 'GET|HEAD',
                'prefix' => 'users',
            ],
            [
                'name' => 'users.store',
                'action' => 'App\Http\Controllers\UserController@store',
                'route' => 'users.store',
                'url' => 'admin/users',
                'method' => 'POST',
                'prefix' => 'users',
            ],
            [
                'name' => 'users.show',
                'action' => 'App\Http\Controllers\UserController@show',
                'route' => 'users.show',
                'url' => 'admin/users/{user}',
                'method' => 'GET|HEAD',
                'prefix' => 'users',
            ],
            [
                'name' => 'users.edit',
                'action' => 'App\Http\Controllers\UserController@edit',
                'route' => 'users.edit',
                'url' => 'admin/users/{user}/edit',
                'method' => 'GET|HEAD',
                'prefix' => 'users',
            ],
            [
                'name' => 'users.update',
                'action' => 'App\Http\Controllers\UserController@update',
                'route' => 'users.update',
                'url' => 'admin/users/{user}',
                'method' => 'PUT|PATCH',
                'prefix' => 'users',
            ],
            [
                'name' => 'users.destroy',
                'action' => 'App\Http\Controllers\UserController@destroy',
                'route' => 'users.destroy',
                'url' => 'admin/users/{user}',
                'method' => 'DELETE',
                'prefix' => 'users',
            ],
            [
                'name' => 'lawyer.index',
                'action' => 'App\Http\Controllers\UserController@index',
                'route' => 'lawyer.index',
                'url' => 'admin/lawyer',
                'method' => 'GET|HEAD',
                'prefix' => 'lawyer',
            ],
            [
                'name' => 'lawyer.create',
                'action' => 'App\Http\Controllers\UserController@create',
                'route' => 'lawyer.create',
                'url' => 'admin/lawyer/create',
                'method' => 'GET|HEAD',
                'prefix' => 'lawyer',
            ],
            [
                'name' => 'lawyer.store',
                'action' => 'App\Http\Controllers\UserController@store',
                'route' => 'lawyer.store',
                'url' => 'admin/lawyer',
                'method' => 'POST',
                'prefix' => 'lawyer',
            ],
            [
                'name' => 'lawyer.show',
                'action' => 'App\Http\Controllers\UserController@show',
                'route' => 'lawyer.show',
                'url' => 'admin/lawyer/{lawyer}',
                'method' => 'GET|HEAD',
                'prefix' => 'lawyer',
            ],
            [
                'name' => 'lawyer.edit',
                'action' => 'App\Http\Controllers\UserController@edit',
                'route' => 'lawyer.edit',
                'url' => 'admin/lawyer/{lawyer}/edit',
                'method' => 'GET|HEAD',
                'prefix' => 'lawyer',
            ],
            [
                'name' => 'lawyer.update',
                'action' => 'App\Http\Controllers\UserController@update',
                'route' => 'lawyer.update',
                'url' => 'admin/lawyer/{lawyer}',
                'method' => 'PUT|PATCH',
                'prefix' => 'lawyer',
            ],
            [
                'name' => 'lawyer.destroy',
                'action' => 'App\Http\Controllers\UserController@destroy',
                'route' => 'lawyer.destroy',
                'url' => 'admin/lawyer/{lawyer}',
                'method' => 'DELETE',
                'prefix' => 'lawyer',
            ],
            [
                'name' => 'lawyers.index',
                'action' => 'App\Http\Controllers\LawyerController@index',
                'route' => 'lawyers.index',
                'url' => 'admin/lawyers',
                'method' => 'GET|HEAD',
                'prefix' => 'lawyers',
            ],
            [
                'name' => 'lawyers.create',
                'action' => 'App\Http\Controllers\LawyerController@create',
                'route' => 'lawyers.create',
                'url' => 'admin/lawyers/create',
                'method' => 'GET|HEAD',
                'prefix' => 'lawyers',
            ],
            [
                'name' => 'lawyers.store',
                'action' => 'App\Http\Controllers\LawyerController@store',
                'route' => 'lawyers.store',
                'url' => 'admin/lawyers',
                'method' => 'POST',
                'prefix' => 'lawyers',
            ],
            [
                'name' => 'lawyers.show',
                'action' => 'App\Http\Controllers\LawyerController@show',
                'route' => 'lawyers.show',
                'url' => 'admin/lawyers/{lawyer}',
                'method' => 'GET|HEAD',
                'prefix' => 'lawyers',
            ],
            [
                'name' => 'lawyers.edit',
                'action' => 'App\Http\Controllers\LawyerController@edit',
                'route' => 'lawyers.edit',
                'url' => 'admin/lawyers/{lawyer}/edit',
                'method' => 'GET|HEAD',
                'prefix' => 'lawyers',
            ],
            [
                'name' => 'lawyers.update',
                'action' => 'App\Http\Controllers\LawyerController@update',
                'route' => 'lawyers.update',
                'url' => 'admin/lawyers/{lawyer}',
                'method' => 'PUT|PATCH',
                'prefix' => 'lawyers',
            ],
            [
                'name' => 'lawyers.destroy',
                'action' => 'App\Http\Controllers\LawyerController@destroy',
                'route' => 'lawyers.destroy',
                'url' => 'admin/lawyers/{lawyer}',
                'method' => 'DELETE',
                'prefix' => 'lawyers',
            ],
            [
                'name' => 'roles.index',
                'action' => 'App\Http\Controllers\RoleController@index',
                'route' => 'roles.index',
                'url' => 'admin/roles',
                'method' => 'GET|HEAD',
                'prefix' => 'roles',
            ],
            [
                'name' => 'roles.create',
                'action' => 'App\Http\Controllers\RoleController@create',
                'route' => 'roles.create',
                'url' => 'admin/roles/create',
                'method' => 'GET|HEAD',
                'prefix' => 'roles',
            ],
            [
                'name' => 'roles.store',
                'action' => 'App\Http\Controllers\RoleController@store',
                'route' => 'roles.store',
                'url' => 'admin/roles',
                'method' => 'POST',
                'prefix' => 'roles',
            ],
            [
                'name' => 'roles.show',
                'action' => 'App\Http\Controllers\RoleController@show',
                'route' => 'roles.show',
                'url' => 'admin/roles/{role}',
                'method' => 'GET|HEAD',
                'prefix' => 'roles',
            ],
            [
                'name' => 'roles.edit',
                'action' => 'App\Http\Controllers\RoleController@edit',
                'route' => 'roles.edit',
                'url' => 'admin/roles/{role}/edit',
                'method' => 'GET|HEAD',
                'prefix' => 'roles',
            ],
            [
                'name' => 'roles.update',
                'action' => 'App\Http\Controllers\RoleController@update',
                'route' => 'roles.update',
                'url' => 'admin/roles/{role}',
                'method' => 'PUT|PATCH',
                'prefix' => 'roles',
            ],
            [
                'name' => 'roles.destroy',
                'action' => 'App\Http\Controllers\RoleController@destroy',
                'route' => 'roles.destroy',
                'url' => 'admin/roles/{role}',
                'method' => 'DELETE',
                'prefix' => 'roles',
            ],
            [
                'name' => 'active.user',
                'action' => 'App\Http\Controllers\UserController@activeUser',
                'route' => 'active.user',
                'url' => 'admin/user-list',
                'method' => 'GET|HEAD',
                'prefix' => 'active',
            ],
            [
                'name' => 'profile.edit',
                'action' => 'App\Http\Controllers\ProfileController@edit',
                'route' => 'profile.edit',
                'url' => 'profile',
                'method' => 'GET|HEAD',
                'prefix' => 'profile',
            ],
            [
                'name' => 'profile.update',
                'action' => 'App\Http\Controllers\ProfileController@update',
                'route' => 'profile.update',
                'url' => 'profile',
                'method' => 'PATCH',
                'prefix' => 'profile',
            ],
            [
                'name' => 'profile.destroy',
                'action' => 'App\Http\Controllers\ProfileController@destroy',
                'route' => 'profile.destroy',
                'url' => 'profile',
                'method' => 'DELETE',
                'prefix' => 'profile',
            ],
            [
                'name' => 'clients.index',
                'action' => 'App\Http\Controllers\ClientController@index',
                'route' => 'clients.index',
                'url' => 'clients/clients',
                'method' => 'GET|HEAD',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.create',
                'action' => 'App\Http\Controllers\ClientController@create',
                'route' => 'clients.create',
                'url' => 'clients/clients/create',
                'method' => 'GET|HEAD',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.store',
                'action' => 'App\Http\Controllers\ClientController@store',
                'route' => 'clients.store',
                'url' => 'clients/clients',
                'method' => 'POST',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.show',
                'action' => 'App\Http\Controllers\ClientController@show',
                'route' => 'clients.show',
                'url' => 'clients/clients/{client}',
                'method' => 'GET|HEAD',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.edit',
                'action' => 'App\Http\Controllers\ClientController@edit',
                'route' => 'clients.edit',
                'url' => 'clients/clients/{client}/edit',
                'method' => 'GET|HEAD',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.update',
                'action' => 'App\Http\Controllers\ClientController@update',
                'route' => 'clients.update',
                'url' => 'clients/clients/{client}',
                'method' => 'PUT|PATCH',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.destroy',
                'action' => 'App\Http\Controllers\ClientController@destroy',
                'route' => 'clients.destroy',
                'url' => 'clients/clients/{client}',
                'method' => 'DELETE',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.file.store',
                'action' => 'App\Http\Controllers\ClientController@fileStore',
                'route' => 'clients.file.store',
                'url' => 'clients/file',
                'method' => 'POST',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.file.update',
                'action' => 'App\Http\Controllers\ClientController@fileUpdate',
                'route' => 'clients.file.update',
                'url' => 'clients/file-update',
                'method' => 'POST',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.hearing.date',
                'action' => 'App\Http\Controllers\CaseController@hearingDate',
                'route' => 'clients.hearing.date',
                'url' => 'clients/hearing-date',
                'method' => 'POST',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.hearing.edit',
                'action' => 'App\Http\Controllers\CaseController@hearingEdit',
                'route' => 'clients.hearing.edit',
                'url' => 'clients/hearing/edit/{id}',
                'method' => 'GET|HEAD',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.hearing.update',
                'action' => 'App\Http\Controllers\CaseController@hearingUpdate',
                'route' => 'clients.hearing.update',
                'url' => 'clients/hearing/update/{id}',
                'method' => 'POST',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.import',
                'action' => 'App\Http\Controllers\ClientController@import',
                'route' => 'clients.import',
                'url' => 'clients/clients/import',
                'method' => 'POST',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.entry',
                'action' => 'App\Http\Controllers\TmpClientController@index',
                'route' => 'clients.entry',
                'url' => 'clients/client/entry',
                'method' => 'GET|HEAD',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.aprove',
                'action' => 'App\Http\Controllers\TmpClientController@aprove',
                'route' => 'clients.aprove',
                'url' => 'clients/client/aprove/{id}',
                'method' => 'GET|HEAD',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.pending',
                'action' => 'App\Http\Controllers\ClientController@pending',
                'route' => 'clients.pending',
                'url' => 'clients/client/pending',
                'method' => 'GET|HEAD',
                'prefix' => 'clients',
            ],
            [
                'name' => 'clients.secrate',
                'action' => 'App\Http\Controllers\ClientController@secrate',
                'route' => 'clients.secrate',
                'url' => 'clients/client/secrate',
                'method' => 'GET|HEAD',
                'prefix' => 'clients',
            ],
            [
                'name' => 'caseType.index',
                'action' => 'App\Http\Controllers\CaseTypeController@index',
                'route' => 'caseType.index',
                'url' => 'config/caseType',
                'method' => 'GET|HEAD',
                'prefix' => 'caseType',
            ],
            [
                'name' => 'caseType.create',
                'action' => 'App\Http\Controllers\CaseTypeController@create',
                'route' => 'caseType.create',
                'url' => 'config/caseType/create',
                'method' => 'GET|HEAD',
                'prefix' => 'caseType',
            ],
            [
                'name' => 'caseType.store',
                'action' => 'App\Http\Controllers\CaseTypeController@store',
                'route' => 'caseType.store',
                'url' => 'config/caseType',
                'method' => 'POST',
                'prefix' => 'caseType',
            ],
            [
                'name' => 'caseType.show',
                'action' => 'App\Http\Controllers\CaseTypeController@show',
                'route' => 'caseType.show',
                'url' => 'config/caseType/{caseType}',
                'method' => 'GET|HEAD',
                'prefix' => 'caseType',
            ],
            [
                'name' => 'caseType.edit',
                'action' => 'App\Http\Controllers\CaseTypeController@edit',
                'route' => 'caseType.edit',
                'url' => 'config/caseType/{caseType}/edit',
                'method' => 'GET|HEAD',
                'prefix' => 'caseType',
            ],
            [
                'name' => 'caseType.update',
                'action' => 'App\Http\Controllers\CaseTypeController@update',
                'route' => 'caseType.update',
                'url' => 'config/caseType/{caseType}',
                'method' => 'PUT|PATCH',
                'prefix' => 'caseType',
            ],
            [
                'name' => 'caseType.destroy',
                'action' => 'App\Http\Controllers\CaseTypeController@destroy',
                'route' => 'caseType.destroy',
                'url' => 'config/caseType/{caseType}',
                'method' => 'DELETE',
                'prefix' => 'caseType',
            ],
            [
                'name' => 'email-setup.index',
                'action' => 'App\Http\Controllers\EmailSetupController@index',
                'route' => 'email-setup.index',
                'url' => 'config/email-setup',
                'method' => 'GET|HEAD',
                'prefix' => 'email-setup',
            ],
            [
                'name' => 'email-setup.create',
                'action' => 'App\Http\Controllers\EmailSetupController@create',
                'route' => 'email-setup.create',
                'url' => 'config/email-setup/create',
                'method' => 'GET|HEAD',
                'prefix' => 'email-setup',
            ],
            [
                'name' => 'email-setup.store',
                'action' => 'App\Http\Controllers\EmailSetupController@store',
                'route' => 'email-setup.store',
                'url' => 'config/email-setup',
                'method' => 'POST',
                'prefix' => 'email-setup',
            ],
            [
                'name' => 'email-setup.show',
                'action' => 'App\Http\Controllers\EmailSetupController@show',
                'route' => 'email-setup.show',
                'url' => 'config/email-setup/{email_setup}',
                'method' => 'GET|HEAD',
                'prefix' => 'email-setup',
            ],
            [
                'name' => 'email-setup.edit',
                'action' => 'App\Http\Controllers\EmailSetupController@edit',
                'route' => 'email-setup.edit',
                'url' => 'config/email-setup/{email_setup}/edit',
                'method' => 'GET|HEAD',
                'prefix' => 'email-setup',
            ],
            [
                'name' => 'email-setup.update',
                'action' => 'App\Http\Controllers\EmailSetupController@update',
                'route' => 'email-setup.update',
                'url' => 'config/email-setup/{email_setup}',
                'method' => 'PUT|PATCH',
                'prefix' => 'email-setup',
            ],
            [
                'name' => 'email-setup.destroy',
                'action' => 'App\Http\Controllers\EmailSetupController@destroy',
                'route' => 'email-setup.destroy',
                'url' => 'config/email-setup/{email_setup}',
                'method' => 'DELETE',
                'prefix' => 'email-setup',
            ],
            [
                'name' => 'notification-setup.index',
                'action' => 'App\Models\NotificationSetup@index',
                'route' => 'notification-setup.index',
                'url' => 'config/notification-setup',
                'method' => 'GET|HEAD',
                'prefix' => 'notification-setup',
            ],
            [
                'name' => 'notification-setup.create',
                'action' => 'App\Models\NotificationSetup@create',
                'route' => 'notification-setup.create',
                'url' => 'config/notification-setup/create',
                'method' => 'GET|HEAD',
                'prefix' => 'notification-setup',
            ],
            [
                'name' => 'notification-setup.store',
                'action' => 'App\Models\NotificationSetup@store',
                'route' => 'notification-setup.store',
                'url' => 'config/notification-setup',
                'method' => 'POST',
                'prefix' => 'notification-setup',
            ],
            [
                'name' => 'notification-setup.show',
                'action' => 'App\Models\NotificationSetup@show',
                'route' => 'notification-setup.show',
                'url' => 'config/notification-setup/{notification_setup}',
                'method' => 'GET|HEAD',
                'prefix' => 'notification-setup',
            ],
            [
                'name' => 'notification-setup.edit',
                'action' => 'App\Models\NotificationSetup@edit',
                'route' => 'notification-setup.edit',
                'url' => 'config/notification-setup/{notification_setup}/edit',
                'method' => 'GET|HEAD',
                'prefix' => 'notification-setup',
            ],
            [
                'name' => 'notification-setup.update',
                'action' => 'App\Models\NotificationSetup@update',
                'route' => 'notification-setup.update',
                'url' => 'config/notification-setup/{notification_setup}',
                'method' => 'PUT|PATCH',
                'prefix' => 'notification-setup',
            ],
            [
                'name' => 'notification-setup.destroy',
                'action' => 'App\Models\NotificationSetup@destroy',
                'route' => 'notification-setup.destroy',
                'url' => 'config/notification-setup/{notification_setup}',
                'method' => 'DELETE',
                'prefix' => 'notification-setup',
            ],
            [
                'name' => 'sms-setup.index',
                'action' => 'App\Http\Controllers\SmsSetupController@index',
                'route' => 'sms-setup.index',
                'url' => 'config/sms-setup',
                'method' => 'GET|HEAD',
                'prefix' => 'sms-setup',
            ],
            [
                'name' => 'sms-setup.create',
                'action' => 'App\Http\Controllers\SmsSetupController@create',
                'route' => 'sms-setup.create',
                'url' => 'config/sms-setup/create',
                'method' => 'GET|HEAD',
                'prefix' => 'sms-setup',
            ],
            [
                'name' => 'sms-setup.store',
                'action' => 'App\Http\Controllers\SmsSetupController@store',
                'route' => 'sms-setup.store',
                'url' => 'config/sms-setup',
                'method' => 'POST',
                'prefix' => 'sms-setup',
            ],
            [
                'name' => 'sms-setup.show',
                'action' => 'App\Http\Controllers\SmsSetupController@show',
                'route' => 'sms-setup.show',
                'url' => 'config/sms-setup/{sms_setup}',
                'method' => 'GET|HEAD',
                'prefix' => 'sms-setup',
            ],
            [
                'name' => 'sms-setup.edit',
                'action' => 'App\Http\Controllers\SmsSetupController@edit',
                'route' => 'sms-setup.edit',
                'url' => 'config/sms-setup/{sms_setup}/edit',
                'method' => 'GET|HEAD',
                'prefix' => 'sms-setup',
            ],
            [
                'name' => 'sms-setup.update',
                'action' => 'App\Http\Controllers\SmsSetupController@update',
                'route' => 'sms-setup.update',
                'url' => 'config/sms-setup/{sms_setup}',
                'method' => 'PUT|PATCH',
                'prefix' => 'sms-setup',
            ],
            [
                'name' => 'sms-setup.destroy',
                'action' => 'App\Http\Controllers\SmsSetupController@destroy',
                'route' => 'sms-setup.destroy',
                'url' => 'config/sms-setup/{sms_setup}',
                'method' => 'DELETE',
                'prefix' => 'sms-setup',
            ],
            [
                'name' => 'call-setup.index',
                'action' => 'App\Http\Controllers\CallSetupController@index',
                'route' => 'call-setup.index',
                'url' => 'config/call-setup',
                'method' => 'GET|HEAD',
                'prefix' => 'call-setup',
            ],
            [
                'name' => 'call-setup.create',
                'action' => 'App\Http\Controllers\CallSetupController@create',
                'route' => 'call-setup.create',
                'url' => 'config/call-setup/create',
                'method' => 'GET|HEAD',
                'prefix' => 'call-setup',
            ],
            [
                'name' => 'call-setup.store',
                'action' => 'App\Http\Controllers\CallSetupController@store',
                'route' => 'call-setup.store',
                'url' => 'config/call-setup',
                'method' => 'POST',
                'prefix' => 'call-setup',
            ],
            [
                'name' => 'call-setup.show',
                'action' => 'App\Http\Controllers\CallSetupController@show',
                'route' => 'call-setup.show',
                'url' => 'config/call-setup/{call_setup}',
                'method' => 'GET|HEAD',
                'prefix' => 'call-setup',
            ],
            [
                'name' => 'call-setup.edit',
                'action' => 'App\Http\Controllers\CallSetupController@edit',
                'route' => 'call-setup.edit',
                'url' => 'config/call-setup/{call_setup}/edit',
                'method' => 'GET|HEAD',
                'prefix' => 'call-setup',
            ],
            [
                'name' => 'call-setup.update',
                'action' => 'App\Http\Controllers\CallSetupController@update',
                'route' => 'call-setup.update',
                'url' => 'config/call-setup/{call_setup}',
                'method' => 'PUT|PATCH',
                'prefix' => 'call-setup',
            ],
            [
                'name' => 'call-setup.destroy',
                'action' => 'App\Http\Controllers\CallSetupController@destroy',
                'route' => 'call-setup.destroy',
                'url' => 'config/call-setup/{call_setup}',
                'method' => 'DELETE',
                'prefix' => 'call-setup',
            ],
            [
                'name' => 'record.delete',
                'action' => 'App\Http\Controllers\BasicController@deleteRecord',
                'route' => 'record.delete',
                'url' => 'record/delete',
                'method' => 'GET|HEAD',
                'prefix' => 'record',
            ],
            [
                'name' => 'users.change.password',
                'action' => 'App\Http\Controllers\UserController@changePassword',
                'route' => 'users.change.password',
                'url' => 'change/password/{id}',
                'method' => 'GET|HEAD',
                'prefix' => 'users',
            ],
            [
                'name' => 'notify',
                'action' => 'App\Http\Controllers\BasicController@notify',
                'route' => 'notify',
                'url' => 'notification/all',
                'method' => 'GET|HEAD',
                'prefix' => 'notify',
            ],
            [
                'name' => 'markasread',
                'action' => 'App\Http\Controllers\BasicController@markAsRead',
                'route' => 'markasread',
                'url' => 'notification/mark-as-read/{id}',
                'method' => 'GET|HEAD',
                'prefix' => 'markasread',
            ],
            [
                'name' => '',
                'action' => 'Closure',
                'route' => '',
                'url' => 'migrate-fresh',
                'method' => 'GET|HEAD',
                'prefix' => '',
            ],
            [
                'name' => '',
                'action' => 'Closure',
                'route' => '',
                'url' => 'migrate',
                'method' => 'GET|HEAD',
                'prefix' => '',
            ],
            [
                'name' => 'register',
                'action' => 'App\Http\Controllers\Auth\RegisteredUserController@create',
                'route' => 'register',
                'url' => 'register',
                'method' => 'GET|HEAD',
                'prefix' => 'register',
            ],
            [
                'name' => '',
                'action' => 'App\Http\Controllers\Auth\RegisteredUserController@store',
                'route' => '',
                'url' => 'register',
                'method' => 'POST',
                'prefix' => '',
            ],
            [
                'name' => 'login',
                'action' => 'App\Http\Controllers\Auth\AuthenticatedSessionController@create',
                'route' => 'login',
                'url' => 'login',
                'method' => 'GET|HEAD',
                'prefix' => 'login',
            ],
            [
                'name' => '',
                'action' => 'App\Http\Controllers\Auth\AuthenticatedSessionController@store',
                'route' => '',
                'url' => 'login',
                'method' => 'POST',
                'prefix' => '',
            ],
            [
                'name' => 'password.request',
                'action' => 'App\Http\Controllers\Auth\PasswordResetLinkController@create',
                'route' => 'password.request',
                'url' => 'forgot-password',
                'method' => 'GET|HEAD',
                'prefix' => 'password',
            ],
            [
                'name' => 'password.email',
                'action' => 'App\Http\Controllers\Auth\PasswordResetLinkController@store',
                'route' => 'password.email',
                'url' => 'forgot-password',
                'method' => 'POST',
                'prefix' => 'password',
            ],
            [
                'name' => 'password.reset',
                'action' => 'App\Http\Controllers\Auth\NewPasswordController@create',
                'route' => 'password.reset',
                'url' => 'reset-password/{token}',
                'method' => 'GET|HEAD',
                'prefix' => 'password',
            ],
            [
                'name' => 'password.store',
                'action' => 'App\Http\Controllers\Auth\NewPasswordController@store',
                'route' => 'password.store',
                'url' => 'reset-password',
                'method' => 'POST',
                'prefix' => 'password',
            ],
            [
                'name' => 'verification.notice',
                'action' => 'App\Http\Controllers\Auth\EmailVerificationPromptController',
                'route' => 'verification.notice',
                'url' => 'verify-email',
                'method' => 'GET|HEAD',
                'prefix' => 'verification',
            ],
            [
                'name' => 'verification.verify',
                'action' => 'App\Http\Controllers\Auth\VerifyEmailController',
                'route' => 'verification.verify',
                'url' => 'verify-email/{id}/{hash}',
                'method' => 'GET|HEAD',
                'prefix' => 'verification',
            ],
            [
                'name' => 'verification.send',
                'action' => 'App\Http\Controllers\Auth\EmailVerificationNotificationController@store',
                'route' => 'verification.send',
                'url' => 'email/verification-notification',
                'method' => 'POST',
                'prefix' => 'verification',
            ],
            [
                'name' => 'password.confirm',
                'action' => 'App\Http\Controllers\Auth\ConfirmablePasswordController@show',
                'route' => 'password.confirm',
                'url' => 'confirm-password',
                'method' => 'GET|HEAD',
                'prefix' => 'password',
            ],
            [
                'name' => '',
                'action' => 'App\Http\Controllers\Auth\ConfirmablePasswordController@store',
                'route' => '',
                'url' => 'confirm-password',
                'method' => 'POST',
                'prefix' => '',
            ],
            [
                'name' => 'password.update',
                'action' => 'App\Http\Controllers\Auth\PasswordController@update',
                'route' => 'password.update',
                'url' => 'password',
                'method' => 'PUT',
                'prefix' => 'password',
            ],
            [
                'name' => 'logout',
                'action' => 'App\Http\Controllers\Auth\AuthenticatedSessionController@destroy',
                'route' => 'logout',
                'url' => 'logout',
                'method' => 'POST',
                'prefix' => 'logout',
            ],
        ];

        $data = []; // Initialize an empty array to store created permissions
        $null = []; // Initialize an empty array to store null route information

        foreach ($permission as $info) {
            if ($info['route'] != null) {
                $createdPermission = Permission::query()->create($info); // Create permission
                $data[] = $createdPermission; // Add the created permission object to the array
            } else {
                $null[] = $info; // Add null route info to the $null array
            }
        }

        // Extract the 'id' of each created permission
        $ids = collect($data)->pluck('id'); // Use 'collect' to treat the array as a collection
        $ids = $ids->toArray(); // Convert the collection to an array
        $role = Role::query()->create(['name'=>'Super Admin']);
        $role->permissions()->sync($ids); // Assign the created permissions to the 'Super Admin
        $user = User::query()->get();
        foreach ($user as $user) {
            $user->roles()->attach($role->id);
        }


    }

}
